version: "3.9"
services:
  discovery:
   build: ../Eureka_Server
   ports:
    - "8761:8761"
   image: "discovery-service"
   
#  apigateway:
#    image: "apigateway"
#    build: ../apigateway
#    ports:
#      - "8080:8080"
#    hostname: APIgateway
#    environment:
#      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
#
#    depends_on:
#      - "discovery"
      
     
      
  candidate_B:
   build: ../candidate
   environment:
   - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
   ports:
   - "8090:8090"
   image: "candidate-service"
  

     
 


  
  # nodebackend:
   # depends_on: 
     # - "mysqldb"
   # container_name: nodebackend
   # image: "authimage"
   # build: ../nodebackenddocker/server
   # ports:
     # - "3001:3001"
   # hostname: nodebackend
   # environment:
      # - DB_HOST=mysqldb
      # - DB_USER=root
      # - DB_PASSWORD=""
      # - DB_NAME=internshipdb
      # - DB_PORT=3308
   # command: "node index.js"
   

